# Generated by Django 3.2.23 on 2024-01-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20240117_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('street_address1', models.CharField(max_length=255)),
                ('street_address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=255)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('poster_size', models.CharField(blank=True, max_length=10)),
                ('order_item_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='checkout.order')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.poster')),
            ],
        ),
    ]
